version: "3"
services:
  app:
    container_name: app_rabbit_producer
    build: .
    volumes:
      - app-data-entry:/entry
      - app-data-output:/output
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
      - app2

  app2:
    container_name: app_rabbit_consumer
    build: ./consumer
    volumes:
      - app-data-entry:/entry
      - app-data-output:/output
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbit
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  app-data-entry:
  app-data-output:
